### ISSUE TITLE
Connect plugin - type errors when connections are saved in Hawtio v1 format

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-integration#87] opened 2019-09-26 05:55 UTC
When I open Connect tab using `java -jar hawtio-app-2.8-SNAPSHOT.jar` I keep seeing the following type errors on browser console:

![Screenshot from 2019-09-26 14-50-44](https://user-images.githubusercontent.com/156692/65661718-55f9c480-e06d-11e9-8044-746abe88e158.png)

@alexkieling Do you have any ideas why it keeps showing up?

**Comment by alexkieling** [comment] 2019-09-26 11:37
What browser (name & version) are you using and what page(s) trigger this error?

**Comment by jamesnetherton** [comment] 2019-09-26 11:51
Could be a duplicate of https://github.com/hawtio/hawtio/issues/2585.

**Comment by alexkieling** [comment] 2019-09-26 22:32
Good point. The code expects `t` to be a String but it's something else. Try to find out what `t` is in the source code.

**Comment by tadayosi** [comment] 2019-09-27 01:26
Thanks guys! That's exactly hawtio/hawtio#2585. Cleaning up local storage and the issue disappears. I forgot that I was working on Hawtio v1 issue...

**Comment by alexkieling** [comment] 2019-09-27 09:34
We could write some code to check the data type and avoid this error.

**Comment by tadayosi** [comment] 2019-09-30 07:35
I like the idea. Let's reopen it.

**Closed** 2019-10-22 14:44 UTC
